package de.lambda9.ready2race.backend.calls.responses

enum class ErrorCode {
    /**
     * Ein Defekt, kein fachlicher Fehler. Wird nicht beantwortet, sondern vom automatischen
     * RaceClocker-Abruf in `competition_match.raceclocker_poll_error` abgelegt, wenn ein Lauf an
     * etwas gescheitert ist, das keinen eigenen Code hat (typischerweise ein `orDie`-Fehlschlag in
     * SQL). Die Oberfläche zeigt dafür „Unerwarteter Fehler" - der Grund steht im Server-Log.
     */
    INTERNAL_ERROR,

    CANNOT_ASSIGN_ROLES,
    CAPTCHA_WRONG,
    EMAIL_IN_USE,
    INVOICES_ALREADY_PRODUCED,
    NO_ASSIGNED_PAYEE_INFORMATION,
    NO_ASSIGNED_CONTACT_INFORMATION,

    EVENT_REGISTRATION_ONGOING,
    EVENT_REGISTRATION_CLOSED,
    EVENT_REGISTRATION_UPSERT_PARTICIPANT_NOT_FOUND,
    EVENT_REGISTRATION_TEAM_PARTICIPANT_NOT_FOUND,
    EVENT_REGISTRATION_COMPETITION_NOT_FOUND,
    EVENT_REGISTRATION_NAMED_PARTICIPANT_NOT_FOUND,
    EVENT_REGISTRATION_FEE_NOT_FOUND,
    EVENT_REGISTRATION_RATING_CATEGORY_NOT_FOUND,
    EVENT_REGISTRATION_RATING_CATEGORY_MISSING,
    EVENT_REGISTRATION_AGE_REQUIREMENT_NOT_MET,
    EVENT_REGISTRATION_PARTICIPANT_DUPLICATE_IN_COMPETITION,

    FILE_ERROR,

    SPREADSHEET_MALFORMED,
    SPREADSHEET_NO_HEADERS,
    SPREADSHEET_COLUMN_UNKNOWN,
    SPREADSHEET_CELL_BLANK,
    SPREADSHEET_WRONG_CELL_TYPE,
    SPREADSHEET_UNPARSABLE_STRING,

    WRONG_TEAM_COUNT,
    DUPLICATE_START_NUMBERS,
    DUPLICATE_TEAMS,
    DUPLICATE_PLACES,
    PLACES_UNCONTINUOUS,

    LIST_DATA_INCOMPLETE,
    RESULT_NOT_FAILED_AND_NO_DATA,

    PARTICIPANT_IMPORT_UNKNOWN_GENDER_VALUE,

    CLUB_NAME_ALREADY_EXISTS,

    RACECLOCKER_URL_MISSING,
    RACECLOCKER_URL_INVALID,
    RACECLOCKER_UNREACHABLE,
    RACECLOCKER_MALFORMED_FEED,
    RACECLOCKER_MATCH_NOT_IN_FEED,
    RACECLOCKER_DUPLICATE_TEAMS,
    RACECLOCKER_NO_RESULTS,
    RACECLOCKER_MATCH_IS_BYE,
    STARTLIST_CONFIG_NOT_CONFIGURED,
    RESULT_IMPORT_CONFIG_NOT_CONFIGURED,

    SCHEDULE_SHIFT_WITHOUT_CHANGE,
    SCHEDULE_SHIFT_TARGET_INVALID,
    SCHEDULE_SHIFT_LEAVES_RACE_DAY,
    SCHEDULE_SHIFT_OVERTAKES_PREDECESSOR,
    SCHEDULE_ADVANCE_NO_DELTA,
    SCHEDULE_SLOT_NOT_SKIPPED,
    SCHEDULE_IMPORT_DUPLICATE_ROWS,
    SCHEDULE_COMPRESSION_IMPOSSIBLE,
    SCHEDULE_SETUP_MATCH_ALREADY_PLANNED,
    SCHEDULE_SLOT_MATCH_ALREADY_STARTED,
    SCHEDULE_SLOT_MATCH_ALREADY_FINISHED,
    SCHEDULE_SLOT_NOT_SKIPPABLE,
    SCHEDULE_SLOT_NOT_LINKED,
    SCHEDULE_ROUND_NOT_MATERIALIZED,
    SCHEDULE_ROUND_HAS_RUNS_TO_RACE,

    CERTIFICATE_NO_RESULTS,
    CERTIFICATE_MISSING_TEMPLATE,
    CERTIFICATE_UNREADABLE_TEMPLATE,
    CERTIFICATE_NOT_A_CHALLENGE_EVENT,
    CERTIFICATE_CHALLENGE_STILL_IN_PROGRESS,

    AWARD_CERTIFICATE_NO_RESULTS,
    AWARD_CERTIFICATE_MISSING_TEMPLATE,
    AWARD_CERTIFICATE_UNREADABLE_TEMPLATE,
    AWARD_CERTIFICATE_COMPETITION_NOT_IN_EVENT,
    AWARD_CERTIFICATE_IS_CHALLENGE_EVENT,

    DOCUMENT_TEMPLATE_INVALID_FONT,
    DOCUMENT_TEMPLATE_TYPE_MISMATCH,
    DOCUMENT_TEMPLATE_PLACEHOLDER_PAGE_NOT_SUPPORTED,
    DOCUMENT_TEMPLATE_PLACEHOLDER_TYPE_NOT_SUPPORTED,
    DOCUMENT_TEMPLATE_INVALID_PDF,
    DOCUMENT_TEMPLATE_INVALID_PACKAGE,
    DOCUMENT_TEMPLATE_UNSUPPORTED_PACKAGE_VERSION,

    SUBSTITUTION_NOT_FOUND,
    SUBSTITUTION_PARTICIPANT_OUT_NOT_FOUND,
    SUBSTITUTION_PARTICIPANT_IN_NOT_FOUND,
    SUBSTITUTION_PARTICIPANT_OUT_NOT_AVAILABLE,
    SUBSTITUTION_PARTICIPANT_IN_NOT_AVAILABLE,
    SUBSTITUTION_DEPENDENT_FOUND,
    SUBSTITUTION_CREATED_IN_PREVIOUS_ROUND,

    CHALLENGE_NOT_A_CHALLENGE_EVENT,
    CHALLENGE_ALREADY_STARTED,
    CHALLENGE_NOT_STARTED_YET,
    CHALLENGE_CORRUPTED_SETUP,
    CHALLENGE_RESULT_ALREADY_SUBMITTED,
    CHALLENGE_NO_RESULT_SUBMITTED,
    CHALLENGE_SELF_SUBMISSION_NOT_ALLOWED,

    EXECUTION_TEAMS_NOT_MATCHING,
    EXECUTION_MATCH_RESULTS_LOCKED,
    EXECUTION_MATCH_IS_BYE,
    EXECUTION_PLACES_NOT_CONTINUOUS,
    EXECUTION_START_TIME_MANAGED_BY_SCHEDULE,

    LIVE_DASHBOARD_FINISH_RESERVED_FOR_OFFICE,

    QR_CODE_ALREADY_IN_USE,

    TRACKING_TEAM_ALREADY_CHECKED_IN,
    TRACKING_TEAM_NOT_CHECKED_IN,
    TRACKING_QR_CODE_NOT_FOUND,
    TRACKING_QR_CODE_NOT_ASSOCIATED_WITH_PARTICIPANT,
    TRACKING_ENTRY_NOT_FOUND,
    TRACKING_SEQUENCE_CONFLICT,
    TRACKING_TIMESTAMP_COLLISION,

    DEREGISTRATION_ALREADY_EXISTS,
    DEREGISTRATION_IS_LOCKED,
    DEREGISTRATION_RESULTS_ALREADY_EXIST,
    DEREGISTRATION_NOT_IN_CURRENT_ROUND,
    DEREGISTRATION_REGISTRATION_STILL_OPEN,
}